import Head from "next/head";
import Image from "next/image";
import Email from "../components/Email";
import SignUpForm from "../components/SignUpForm";
import SocialMedia from "../components/SocialMedia";
import Telephone from "../components/Telephone";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Auto 🚖</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Vehicle Maintenance From the Comfort of Your Home
        </h1>

        <p className={styles.description}>
          Open Auto Soothes the hassle of maintaining your vehicle and helps you
          deal with unexpected repairs worry-free.
        </p>
        <article>
          <SignUpForm />
        </article>
        <article>
          <section>
            <Image
              src="/Pickup_Illustration.png"
              alt="Illustration"
              width={1000}
              height={1000}
            />
          </section>
        </article>
        <article className={styles.grid}>
          <section className={styles.logo}>
            <Image
              src="/openauto.svg"
              alt="Open Auto Logo"
              width={16}
              height={16}
            />
          </section>
          <section>
            <Telephone />
          </section>
          <section>
            <Email />
          </section>
          <section>
            <SocialMedia />
          </section>
        </article>

        <article className={styles.grid}>
          <section>
            <h1 className={styles.title}>Focused on Time Saving</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
              dignissim mi nisl, ac luctus ipsum pellentesque in. Praesent
              pharetra, magna et cursus varius, elit est auctor elit, ac
              hendrerit urna diam sit amet quam. Suspendisse quis arcu ac odio
              hendrerit rutrum vitae vitae enim. Phasellus tortor neque,
              venenatis eu hendrerit vitae, scelerisque eu tortor. Donec
              faucibus leo at quam iaculis, pulvinar fermentum libero semper.
              Suspendisse sodales lorem quis mi faucibus, ut vulputate leo
              bibendum. Maecenas ut dignissim lorem, at ultricies arcu. Duis
              vitae libero semper, commodo tortor at, ullamcorper neque. Integer
              eu tempus nulla.
            </p>
          </section>
          <section>
            <Image
              src="/Phone.svg"
              alt="Pick Up Service Phone Banner"
              width={1000}
              height={1000}
            />
          </section>
        </article>
      </main>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          <span className={styles.logo}>
            <Image
              src="/openauto-brand.svg"
              alt="Open Auto Branding"
              width={67}
              height={18}
            />
          </span>
          Open Auto @ all rights reserved{" "}
        </a>
        <article className={styles.grid}>
          <section>
            <Telephone />
          </section>
          <section>
            <Email />{" "}
          </section>
          <section>
            <SocialMedia />
          </section>
        </article>
      </footer>
    </div>
  );
}
